version: 2
updates:
  # Set update schedule for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every month
      interval: 'monthly'
    groups:
      actions:
        patterns:
          - '*'
