github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
tasks:
  - name: setup
    init: |
      pushd /workspace
      wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      popd
      # bootstrap activation commands for other tasks to reuse
      cat <<EOT > /workspace/bin/activate-env.sh
      export MAMBA_ROOT_PREFIX=/workspace/.micromamba
      export MAMBA_EXE=/workspace/bin/micromamba
      $(/workspace/bin/micromamba shell hook --shell=bash)
      export JUPYTER_PREFER_ENV_PATH=1
      micromamba activate
      EOT
      source /workspace/bin/activate-env.sh
      micromamba config append channels conda-forge
      micromamba install -n base -y -f .binder/environment.yml
      source /workspace/bin/activate-env.sh
      doit build
    command: |
      gp sync-done setup
      source /workspace/bin/activate-env.sh
      doit watch
  - name: watch
    command: |
      gp sync-await setup
      source /workspace/bin/activate-env.sh
      doit serve
  - name: docs
    command: |
      gp sync-await setup
      source /workspace/bin/activate-env.sh
      doit watch:docs
  - name: auto-activate
    command: |
      gp sync-await setup
      echo "source /workspace/bin/activate-env.sh" >> ~/.bashrc
      source /workspace/bin/activate-env.sh
ports:
  - port: 5000
  - port: 8000
  - port: 8888
