version: 2
build:
  os: ubuntu-24.04
  tools:
    python: '3.12'
    nodejs: '24'
  jobs:
    post_install:
      - python -m pip install --upgrade pip
      - python -m pip install --group docs --group dev -r examples/requirements-demo.txt
      - jlpm
      - jlpm build
      - jlpm pack:app
      - python -m pip install './py/jupyterlite-core[all]'
      - jlpm build:py
      - jlpm docs
      - jupyter lite build --contents examples --output-dir build/docs-app
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
