#!/usr/bin/env bash
set -eux

yarn
yarn build

# enable the proxy
for app in notebook server; do
    mkdir -p ${CONDA_DIR}/etc/jupyter/jupyter_${app}_config.d
    cp .binder/jupyterlite-proxy.json ${CONDA_DIR}/etc/jupyter/jupyter_{app}_config.d
done
