name: 'Build JupyterLite'
description: 'Build JupyterLite from source'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Setup pip (base)
      shell: bash
      run: python3 -m pip install --user -U pip setuptools wheel

    - name: Setup pip (build)
      shell: bash
      run: python3 -m pip install -r requirements-build.txt
 
    - name: Install
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: doit setup:js

    - name: Build (js)
      shell: bash
      run: doit -n4 build:js* || doit build:js*

    - name: Build (py)
      shell: bash
      run: doit -n4 build:py*

    - name: Dist
      shell: bash
      run: doit dist
