// this file is autogenerated from the wheels described in ../package.json
export * as allJSONUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/all.json';
export * as ipykernelWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/ipykernel-6.15.1-py3-none-any.whl';
export * as jupyterlabWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/jupyterlab-3.4.4-py3-none-any.whl';
export * as notebookWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/notebook-6.4.2-py3-none-any.whl';
export * as pipliteWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/piplite-0.1.0b11-py3-none-any.whl';
export * as pyoliteWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/pyolite-0.1.0b11-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/widgetsnbextension-3.6.0-py3-none-any.whl';
export const PIPLITE_WHEEL = 'piplite-0.1.0b11-py3-none-any.whl';
