// this file is autogenerated from the wheels described in ../package.json
export * as allJSONUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/all.json';
export * as ipykernelWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/ipykernel-6.9.2-py3-none-any.whl';
export * as jediWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/jedi-0.18.2-py3-none-any.whl';
export * as jupyterlab_widgetsWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/jupyterlab_widgets-1.1.2-py3-none-any.whl';
export * as jupyterlab_widgetsWheelUrl1 from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/jupyterlab_widgets-3.0.5-py3-none-any.whl';
export * as pipliteWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/piplite-0.1.0b18-py3-none-any.whl';
export * as prompt_toolkitWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/prompt_toolkit-3.0.36-py3-none-any.whl';
export * as pyoliteWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/pyolite-0.1.0b18-py3-none-any.whl';
export * as repodataJSONUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/repodata.json';
export * as widgetsnbextensionWheelUrl from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/widgetsnbextension-3.6.0-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl1 from '!!file-loader?name=pypi/[name].[ext]&context=.!../pypi/widgetsnbextension-4.0.2-py3-none-any.whl';
export const PIPLITE_WHEEL = 'piplite-0.1.0b18-py3-none-any.whl';
